config/routes.rb
Rails.application.routes.draw do
 
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html
  resources :kittens

  # Defines the root path route ("/")
   root "kittens#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/kitten.rb
class Kitten < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/kittens_controller.rb
class KittensController < ApplicationController
  def show
    @kitten = Kitten.find(params[:id])

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @kitten }
      format.json { render :json => @kitten }
    end
  end

  def index
    @kittens = Kitten.all

    respond_to do |format|
      format.html # index.html.erb
      format.xml  { render :xml => @kittens }
      format.json { render :json => @kittens }
    end
  end

  def new
    @kitten = Kitten.new 
  end

  def create
    @kitten = Kitten.new(kitten_params)

    if @kitten.save
      redirect_to @kitten , notice: "New kitten added"
    else
      render :new, status: :unprocessable_entity 
    end

  end

  def edit
    @kitten = Kitten.find(params[:id])

  end

  def update
    @kitten = Kitten.find(params[:id])

    if @kitten.update(kitten_params)
      redirect_to @kitten , notice: "Kitten changed"
    else
      render :edit, status: :unprocessable_entity 
    end

  end

  def destroy
    @kitten = Kitten.find(params[:id])
    @kitten.destroy

    redirect_to root_path, status: :see_other , notice: "Kitten deleted"
  end

  private 
  def kitten_params
    params.require(:kitten).permit(:name, :age, :cuteness, :softness)
  end 

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/kittens_helper.rb
module KittensHelper
end

app/views/kittens/_form.html.erb
<%= form_with model: kitten do |form| %>
  <div>
    <%= form.label :name %><br>
    <%= form.text_field :name %>
    <% kitten.errors.full_messages_for(:name).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

   <div>
    <%= form.label :age %><br>
    <%= form.number_field :age, in: 1.0..100.0 %>
    <% kitten.errors.full_messages_for(:age).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.label :cuteness %><br>
    <%= form.number_field :cuteness, in: 1.0..10.0 %>
    <% kitten.errors.full_messages_for(:cuteness).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

    <div>
    <%= form.label :softness %><br>
    <%= form.number_field :softness, in: 1.0..10.0 %>
    <% kitten.errors.full_messages_for(:softness).each do |message| %>
      <div><%= message %></div>
    <% end %>
  </div>

  <div>
    <%= form.submit %>
  </div>
<% end %>

app/views/kittens/create.html.erb
<h1>Kittens#create</h1>
<p>Find me in app/views/kittens/create.html.erb</p>

app/views/kittens/destroy.html.erb
<h1>Kittens#destroy</h1>
<p>Find me in app/views/kittens/destroy.html.erb</p>

app/views/kittens/edit.html.erb
<h1>Edit Kitten</h1>

<%= render "form", kitten: @kitten %>

<%= link_to "Destroy", kitten_path(@kitten), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>

app/views/kittens/index.html.erb
<h1>Kittens</h1>

<ul>
  <% @kittens.each do |kitten| %>
    <li>
      <%= link_to kitten.name, kitten %> <br>

      <%= link_to "Destroy", kitten_path(kitten), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %>

      
    </li>
  <% end %>
</ul>

<%= link_to "New Kitten", new_kitten_path %>

app/views/kittens/new.html.erb
<h1>New Kitten</h1>

<%= render "form", kitten: @kitten %>

app/views/kittens/show.html.erb
<h1>This is <%= @kitten.name %></h1>

<p><%= @kitten.age %></p>
<p><%= @kitten.cuteness %></p>
<p><%= @kitten.softness %></p>


<ul>
  <li><%= link_to "Edit", edit_kitten_path(@kitten) %></li>
  <li><%= link_to "Destroy", kitten_path(@kitten), data: {
                    turbo_method: :delete,
                    turbo_confirm: "Are you sure?"
                  } %></li>
</ul>

app/views/kittens/update.html.erb
<h1>Kittens#update</h1>
<p>Find me in app/views/kittens/update.html.erb</p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>OdinKittens</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= render 'shared/flashes' %>
    <%= yield %>
  
  </body>
</html>

app/views/shared/_flashes.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>

app/views/shared/flashes.html.erb
<% flash.each do |type, msg| %>
  <div>
    <%= msg %>
  </div>
<% end %>